### ISSUE TITLE
Assembly error in legfast32.s: ambiguous instructions require an explicit suffix 

### ISSUE THREAD

**Issue by brwst** [Edilbert/PLASIM#1]
Hello all:

I've cloned the PLASIM repository and tried to build PUMA according to the instructions given in the [PUMA Users Guide](https://github.com/Edilbert/PLASIM/blob/master/puma/doc/PUMA_UsersGuide.pdf), but I am running into assembler problems in the Fast Direct Legendre Transformation code.

I first configure the build:

```
$ ./configure.sh
Found FORTRAN-90 compiler     at: /usr/local/bin/gfortran
gfortran version  6.2
Found Xlib (X11)              at: /usr/X11/lib
Found C compiler              at: /usr/local/bin/gcc
Found C++ compiler            at: /usr/local/bin/c++
Found MPI FORTRAN-90 compiler at: /usr/local/bin/mpif90
Found MPI C compiler          at: /usr/local/bin/mpicc
Found MPI C++ compiler        at: /usr/local/bin/mpicxx
Found GNU assembler           at: /usr/bin/as
Fast Legendre Transformation    : ACTIVE (Darwin)
gfortran -o f90check.x f90check.f90
gcc -o cc_check.x cc_check.c

System info for <zissou.local>
Architecture: Darwin zissou.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64 i386 MacBookPro10,1 Darwin
Endian format             : little endian
FORTRAN control word size : 4 bytes
FORTRAN integer size      : 4 bytes
FORTRAN real    size      : 4 bytes
C       int     size      : 4 bytes
C       float   size      : 4 bytes
C       long    size      : 8 bytes
C  long long    size      : 8 bytes
FORTRAN Compiler: gfortran
C       Compiler: gcc
gcc -o most.x most.c -I/usr/X11/include -lm -L/usr/X11/lib -lX11

configuration complete - run <most.x>
```

and subsequently execute `most.x` after following the configuration steps in the Users Guide (select PUMA model, resolution, GUI off, output on, number of years) which results in the following:

```make
$ ./most.x

Using default configuration
gfortran -c -O3 -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -finit-real=snan  puma.f90
gfortran -c -O3 -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -finit-real=snan  mpimod_stub.f90
gfortran -c -O3 -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -finit-real=snan  fftmod.f90
gfortran -c -O3 -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -finit-real=snan  guimod_stub.f90
gcc   -c -O3 -I /usr/X11/include pumax_stub.c
gfortran -c -O3 -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -finit-real=snan  legini.f90
as -o legfast32.o legfast32.s
legfast32.s:517:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,-24(%rbp)      # tn += 2
        ^
legfast32.s:525:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,-16(%rbp)      # fu += 2
        ^
legfast32.s:533:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,-8(%rbp)       # fv += 2
        ^
legfast32.s:541:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,16(%rbp)       # ke += 2
        ^
legfast32.s:552:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,24(%rbp)       # ut += 2
        ^
legfast32.s:560:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,32(%rbp)       # vt += 2
        ^
make: *** [legfast32.o] Error 1
```

I am running Apple OS X 10.11 with GCC 6.2.  I have tried Apple's built-in GCC (which seems to call clang-703.0.31), GCC 4.6 and a GCC 5 without luck.

The error follows the call to the assembler `as` which is not GCC

```
$ as --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

but trying to assemble `legfast32.s` with `gcc` also fails:

```make
$ gcc -o legfast32.o legfast32.s
legfast32.s:517:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,-24(%rbp)      # tn += 2
        ^
legfast32.s:525:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,-16(%rbp)      # fu += 2
        ^
legfast32.s:533:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,-8(%rbp)       # fv += 2
        ^
legfast32.s:541:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,16(%rbp)       # ke += 2
        ^
legfast32.s:552:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,24(%rbp)       # ut += 2
        ^
legfast32.s:560:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
        add     $8,32(%rbp)       # vt += 2
        ^
```

I'm not familiar with assembly, so I apologize if I am missing something basic here.  Perhaps I have a misconfigured environment or there is a compiler flag to set?  Perhaps running OS X 10.11 breaks things?

**Comment by Edilbert** [comment]
Hi Robert,

thanks for the notification.
First of all: It's not your fault.
From time to time compiler and assembler developers introduce new requirements
for the syntax into their software, making it necessary to change
correct code in order to follow their ideas.

Obviously, your system has a very new assembler, which does not assume
the operand size, like the versions before, but expects an
explicitly given operand size.

E.g.:

add     $8,-24(%rbp)     - generic command

must be changed to

addq    $8,-24(%rbp)     - 64 bit add command

This is annoying, because the use of the 64 bit register (%rbp) makes clear,
that a 64 bit operand is in use and the generic command "add" should be
interpreted as the specific command "addq".

I'll change all commands as necessary, in order to keep the assembler happy.
But I've first to download and install your assembler version and test everything.
So I'll update the repository in the beginning of next week.

best wishes and have a nice weekend,

Edilbert



> Am 15.09.2016 um 22:51 schrieb Robert West <notifications@github.com>:
> 
> Hello all:
> 
> I've cloned the PLASIM repository and tried to build PUMA according to the instructions given in the PUMA Users Guide, but I am running into assembler problems in the Fast Direct Legendre Transformation code.
> 
> I first configure the build:
> 
> $ ./configure.sh
> Found FORTRAN-90 compiler     at: /usr/local/bin/gfortran
> gfortran version  6.2
> Found Xlib (X11)              at: /usr/X11/lib
> Found C compiler              at: /usr/local/bin/gcc
> Found C++ compiler            at: /usr/local/bin/c++
> Found MPI FORTRAN-90 compiler at: /usr/local/bin/mpif90
> Found MPI C compiler          at: /usr/local/bin/mpicc
> Found MPI C++ compiler        at: /usr/local/bin/mpicxx
> Found GNU assembler           at: /usr/bin/as
> Fast Legendre Transformation    : ACTIVE (Darwin)
> gfortran -o f90check.x f90check.f90
> gcc -o cc_check.x cc_check.c
> 
> System info for <zissou.local>
> Architecture: Darwin zissou.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64 i386 MacBookPro10,1 Darwin
> Endian format             : little endian
> FORTRAN control word size : 4 bytes
> FORTRAN integer size      : 4 bytes
> FORTRAN real    size      : 4 bytes
> C       int     size      : 4 bytes
> C       float   size      : 4 bytes
> C       long    size      : 8 bytes
> C  long long    size      : 8 bytes
> FORTRAN Compiler: gfortran
> C       Compiler: gcc
> gcc -o most.x most.c -I/usr/X11/include -lm -L/usr/X11/lib -lX11
> 
> configuration complete - run <most.x>
> 
> and subsequently execute most.x after following the configuration steps in the Users Guide (select PUMA model, resolution, GUI off, output on, number of years) which results in the following:
> 
> $ ./most.x
> 
> Using default configuration
> gfortran -c -O3 -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -finit-real=snan  puma.f90
> gfortran -c -O3 -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -finit-real=snan  mpimod_stub.f90
> gfortran -c -O3 -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -finit-real=snan  fftmod.f90
> gfortran -c -O3 -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -finit-real=snan  guimod_stub.f90
> gcc   -c -O3 -I /usr/X11/include pumax_stub.c
> gfortran -c -O3 -ffpe-trap=invalid,zero,overflow -ffpe-summary=none -finit-real=snan  legini.f90
> as -o legfast32.o legfast32.s
> 
> legfast32.s
> :517:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,-24(%rbp)      
> # tn += 2
> 
>         ^
> 
> legfast32.s
> :525:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,-16(%rbp)      
> # fu += 2
> 
>         ^
> 
> legfast32.s
> :533:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,-8(%rbp)       
> # fv += 2
> 
>         ^
> 
> legfast32.s
> :541:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,16(%rbp)       
> # ke += 2
> 
>         ^
> 
> legfast32.s
> :552:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,24(%rbp)       
> # ut += 2
> 
>         ^
> 
> legfast32.s
> :560:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,32(%rbp)       
> # vt += 2
> 
>         ^
> 
> make: *** [legfast32.o] Error 1
> I am running Apple OS X 10.11 with GCC 6.2. I have tried Apple's built-in GCC (which seems to call clang-703.0.31), GCC 4.6 and a GCC 5 without luck.
> 
> The error follows the call to the assembler as which is not GCC
> 
> $ as --version
> Apple LLVM version 7.3.0 (clang-703.0.31)
> Target: x86_64-apple-darwin15.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> 
> but trying to assemble legfast32.s with gcc also fails:
> 
> $ gcc -o legfast32.o legfast32.s
> 
> legfast32.s
> :517:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,-24(%rbp)      
> # tn += 2
> 
>         ^
> 
> legfast32.s
> :525:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,-16(%rbp)      
> # fu += 2
> 
>         ^
> 
> legfast32.s
> :533:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,-8(%rbp)       
> # fv += 2
> 
>         ^
> 
> legfast32.s
> :541:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,16(%rbp)       
> # ke += 2
> 
>         ^
> 
> legfast32.s
> :552:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,24(%rbp)       
> # ut += 2
> 
>         ^
> 
> legfast32.s
> :560:9: error: ambiguous instructions require an explicit suffix (could be 'addb', 'addw', 'addl', or 'addq')
>         add     $8,32(%rbp)       
> # vt += 2
> 
>         ^
> 
> I'm not familiar with assembly, so I apologize if I am missing something basic here. Perhaps I have a misconfigured environment or there is a compiler flag to set? Perhaps running OS X 10.11 breaks things?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



=============
Edilbert Kirk
Univ. Hamburg
Grindelberg 5
20144 Hamburg
040-428385065
=============

**Comment by brwst** [comment]
Hello Edilbert:

Thanks very much for your detailed help and the fix -- I am able to build and run PUMA with the updated changes.
