### ISSUE TITLE
PUMA cannot run correctly with PGI compiler

### ISSUE THREAD

**Issue by wensir365** [Edilbert/PLASIM#2]
Hi Edilbert, 

I found PUMA, a clean 1-CPU serial version with gui_stub and mpi_stub, can be successfully compiled with GNU gfortran (version 5.4, with -O3) and runs correctly. It can also be compiled with PGI pgfortran (the latest version 16.10, with -fast), however, the executable runs incorrectly. The 1st diag info shown in puma_diag, say 1/Jan, is still correct. But the 2nd info, say 11/Jan, become all-star tables. I guess it implies they all burn out. Please see the attachments for this.

More than that, after running the puma.x, 4 warnings pop-up on my screen, like this:
Warning: ieee_invalid is signaling
Warning: ieee_overflow is signaling
Warning: ieee_underflow is signaling
Warning: ieee_inexact is signaling

I try to add some compile options to avoid them, by adding " -Ktrap=fp,ovf,unf,inexact -Kieee", but issues still there.

So, I have to ask for helps from you developers. Do you have any comments on the PGI compiler problem? Why GNU gfortran works so great but PGI compiler cannot?

Appreciate!
Xinyu

[puma_diag.txt](https://github.com/Edilbert/PLASIM/files/907497/puma_diag.txt)
[puma_namelist.txt](https://github.com/Edilbert/PLASIM/files/907496/puma_namelist.txt)

**Comment by Edilbert** [comment]
Hi Xinyu,

I had reports from many users, that he PGI FORTRAN compiler
produces faulty executables for optimizations O2 and greater.
I tested some pieces of codes and found, that the compiler optimizer
has several bugs resulting in wrong executables from completely correct source.

So my recommendation is not to use the PGI compiler, it's buggy.

The best free compiler is gfortran.

The best commercial compiler is the Intel compiler.
The Intel compiler produces executables, which run 4 times faster,
than that of gfortran. The main cause is, that Intel uses a
runtime library which provides support for the SSE and AVX extensions
of modern CPU's.

Best wishes,
Edilbert

> On 8. Apr 2017, at 16:21, Xinyu Wen <notifications@github.com> wrote:
> 
> Hi Edilbert,
> 
> I found PUMA, a clean 1-CPU serial version with gui_stub and mpi_sub, can be successfully compiled with GNU gfortran (version 5.4, with -O3) and runs correctly. It can also be compiled with PGI pgfortran (the latest version 16.10, with -fast), however, the executable runs incorrectly. The 1st diag info shown in puma_diag, say 1/Jan, is still correct. But the 2nd info, say 11/Jan, become all-star tables. I guess it implies they all burn out. Please see the attachments for this.
> 
> More than that, after running the puma.x, 4 warnings pop-up on my screen, like this:
> Warning: ieee_invalid is signaling
> Warning: ieee_overflow is signaling
> Warning: ieee_underflow is signaling
> Warning: ieee_inexact is signaling
> 
> I try to add some compile options to avoid them, by adding " -Ktrap=fp,ovf,unf,inexact -Kieee", but issues still there.
> 
> So, I have to ask for helps from you developers. Do you have any comments on the PGI compiler problem? Why GNU gfortran works so great but PGI compiler cannot?
> 
> Appreciate!
> Xinyu
> 
> puma_diag.txt
> puma_namelist.txt
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



=============
Edilbert Kirk
Univ. Hamburg
Grindelberg 5
20144 Hamburg
040-428385065
=============

**Comment by wensir365** [comment]
Many thanks to you, Dr. Kirk! By the way, do you know which specific lines, or subroutines, or parts caused this optimization problem in PGI compiler?

I agree that Intel compilers always did the unbeatable job in generating high-performance executables. A magic compiler it is.

**Comment by Edilbert** [comment]
> Many thanks to you, Dr. Kirk! By the way, do you know which specific lines, or subroutines, or parts caused this optimization problem in PGI compiler?

See for example this subroutine:

111 !     ============================
112 !     SUBROUTINE GET_RESTART_ARRAY
113 !     ============================
114 
115       subroutine get_restart_array(yn,pa,k1,k2,k3)
116       use restartmod
117 
118       character (len=*) :: yn
119       real :: pa(k2,k3)
120 
121       do j = 1 , nresnum
122          if (trim(yn) == trim(yresnam(j))) then
123             call fileseek(yn,j)
124             read (nreaunit) pa(1:k1,:)
125             nlastrec = nlastrec + 1
126             return
127          endif
128       enddo
129       if (nexcheck == 1) then
130          write(nud,*) '*** Error in get_restart_array ***'
131          write(nud,*) 'Requested array {',yn,'} was not found'
132          stop
133       endif
134       return
135       end subroutine get_restart_array
136 

It is used for 3-dimensional arrays, e.g.

1004          call put_restart_array('sz' ,sz ,NRSP,NESP,NLEV)

or 2-dimensional arrays, e.g.

1009          call put_restart_array('sp' ,sp ,NRSP,NESP,   1)

Standard FORTRAN allows Dimensions to be (1:1) which is the case for
the dummy parameter k3, if called with 2-dim arrays.

The PGI -O3 compiled program does not correctly read the array in the 2nd. case,
with -O0, it works fine.

I'd have rewritten the source, if this was the only issue, but PGI has problems
on many more occasions.

**Comment by wensir365** [comment]
Thanks! I appreciate all your easy-to-follow answers. Your great efforts and puma/plasim have my respect!
